In [4]:
import pandas as pd

df = pd.read_csv('ulasan/Ulasan_Lengkap_Tokopedia.csv')
df

                                                Ulasan
0    Aman, pengiriman cepat, seller ramah dan respo...
1    Barang baru dengan kondisi bagus. Pengiriman d...
2    Barang original segel resmi .adminnya responsi...
3    ini terlalu mantapu ini terlalu mantapu ini te...
4    Barang original pasti. Segel. Garansi. Kartu g...
..                                                 ...
495  barang ORI keren abisss n murah lagi. pokok ya...
496   Original, packaging rapi dan safe.\n👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻
497      packing aman, barang masi d dus, nlm di buka.
498  co kemarin, besok siangnya udah sampe, packing...
499  Iphone 15 nya sampe dengan aman. Barang ORI, t...

[500 rows x 1 columns]

In [1]:
import pandas as pd

df = pd.read_csv('Tokopedia.csv')
df

                                               Ulasan
0         Keren Pokok nya ,Terimakasih. \nGak NyesaL.
1   ukuran pas, desain bagus, sudah ada jahitan di...
2           Mantap kualitas oke buat sekolah adek……..
3   Barang sesuai, Kualitas oke dan ada bantalan l...
4                        mantab pas, pengiriman cepat
5       barang sesuai pesanan dan pengiriman cepat...
6                                              awsome
7                               bagus, nyaman dipakai
8   bagus cuma paking nya kurang rapi, bahan nya b...
9   Topinya bagus bahan tebal penjual jujur sesuai...
10  pengiriman sangat cepattt\nkualitas sepatu bag...
11  Sepatunya bagus, pas dipakainya. Semoga awet. ...
12             barang ok.sampai dengan selamat.bagus.
13                                             mantap
14  sepatunya agak berat dan sakit dipake di bagia...
15  Produk ckp bagus meski ada bagian di sole yg m...
16  bahannya bagus, jahitannya miring;tidk presisi...
17  Semoga awet udh 3x beli dsni 3 bln selalu jebo...
18                                              Cocok
19  alhamdulillah barang nya sudah di terima. sall...
20                             bagus sesuai keinginan
21                  Nyaman dipakai, kualitas bahan ok
22  Kualitas oke buat harganya, packing lumayan am...
23           sepatu nya bagus,rapi ga nyesel beli nya
24  akhirnya sampai juga, satu hari sebelum hari t...
25  Respon seller dan pengiriman perlu di tingkatk...
26  model'a bagus, pengiriman cepat.\n lumayan ena...
27                                              bagus
28  lumayan laahh, warnanya, ukurannya, modelnya, ...
29  paket udh sampai respon seller cepat pengirima...