# Representasi Teks Ulasan Tokopedia
Metode yang digunakan:
1. TF-IDF
2. Word2Vec
3. FastText

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from gensim.models import Word2Vec, FastText
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# Load data ulasan
df = pd.read_csv("Ulasan_Lengkap_Tokopedia.csv")
ulasan = df["Ulasan"].dropna().astype(str).tolist()
ulasan[:500]

['Aman, pengiriman cepat, seller ramah dan responsif, barang aman, dapet bonus case dan anti gores',
 'Barang baru dengan kondisi bagus. Pengiriman dan pengemasan aman dengan sensor deskripsi produk. Garansi resmi dengan kode resmi indonesia',
 'Barang original segel resmi .adminnya responsive banget mantep pokonya ga bakalan ngerasa rugi kalau belanja di toko ini semoga tetep se fast respon ini ya min',
 'ini terlalu mantapu ini terlalu mantapu ini terlalu mantapu ini terlalu mantapu ini terlalu mantapu ini terlalu mantapu ini terlalu mantapu ini terlalu mantapu ini terlalu mantapuini terlalu mantapu ini terlalu mantapu ini terlalu mantapu  ini terlalu mantapu ini terlalu mantapu ini terlalu mantapuini terlalu mantapu ini terlalu mantapu ini terlalu mantapu ini terlalu mantapu ini terlalu mantapu ini terlalu mantapu ini terlalu mantapu ini terlalu mantapu ini terlalu mantapuini terlalu mantapu ini terlalu mantapu ini terlalu mantapu  ini terlalu mantapu ini terlalu mantapu ini terlalu mantapuTutup Ulasan',
 'Barang original pasti. Segel. Garansi. Kartu garansi tercantum dibelakang. Mantab si dapet pas rpomo juga. Thanks tokped! Pas beli lebi murah dibanding retail toko.',
 'pertama kali beli hape lewat aplikasi, Alhamdulillah puas hasilnya.. paket sampai dg selamat, barang masih bersegel dan berfungsi dg baik, kualitas juga bagus bahannya rigit di tangan harga terjangkau dan juga sampai dalam hitungan jam, seller pun ramahTutup Ulasan',
 'admin fast respon banget, sempet ragu dan agak bawel juga karna pengiriman sameday lama. overall bagus banget garansi resmi harga juga beda dari yg lain',
 'barang masih segel, garansi resmi, berfungsi dgn baik, pengiriman (rekomendasi)cepat.. dapat promo',
 'Barang cepet sampai, kualitas bagus, Original, pokoknya the best deh, sellernya cepet tanggep juga',
 'Barang ori, imei terdaftar, garansi ada, mantep banget beli disini lebih murah. Sukses selalu',
 'barang sampai dengan aman. bublewarp nya tebel banget. garansi jelas aman dan udah pasti ori. unboxing langsung segera cek kelengkapan plus update software dan semuanya jalan dengan mulus tanpa kendala. suka banget sama warnanya. rekomended banget beli disini soalnya harga lebih murah dari toko offline.Tutup Ulasan',
 'barang masih di segel, barang sangat rapih di bubble wrapnya tebal, toko tdk memberitahukan driver isi paketnya apa jadi aman, amanah tokonya dan instannya cepat. iphonenya bagus sekali👍Tutup Ulasan',
 'Bareng nya ori masih tersegel dengan baik, sesuai request. Bagus banget pokoknya, semoga awet',
 'kelengkapan oke(kabel charger dan hp doang) apple pelit bet. Pelayanannya bagus, cepet tanggap, ramah juga. Ini toko termurah sih resmi ibox juga(IMEI udah dicek, terdaftar). Pesen kemarin malem, sore tadi dah nyampe pake kurir toko, kurirnya effort bangett padahal lagi hujan deress, makasih banyak lohh👍👍Tutup Ulasan',
 'Mantap barang original dan garansi bisa diclaim',
 'Garansian semua resmi, hanya yg di request kadang ga sesuai. Kiriman juga cepat, deg2an baru pertama kali beli dr OL. Namun sampai di tujuan dg selamat. Makasih seller..',
 'bagus pelayanan penjual. barang ori segel utuh sdh dicoba ok fungsinya..',
 'Barangnya masih segel, kualitas baik, original, pas flash sale milih warna biru eh lagi kosong katanya dan konfirmasi buat ganti warna pink atau hitam. Ku pilih pink karena sbnernya aku emang maunya warna pink, pas banget. Terima kasih seller 👍🏻Tutup Ulasan',
 'Terimakasih barang sudah di terima dalam keadaan baik, kumplit tidak ada yg kurang sesuai pesanan, garansi jg ok Respond penjual cepat, pengiriman jg sangat cepat, semoga barangnya bermanfaat.Tutup Ulasan',
 'terima kasih, alhamdulillah pesanan iphone 15 saya sudah sampai dalam keadaan selamat, dan berfungsi dengan baik, garansi resmi dr ******..semoga awet dan bermanfaat',
 'Produk original sesuai pesanan diterima kondisi dgn baik aman packing super aman berlapis bubble wrap dan harga lebih murah ketika CO wktu itu dibanding toko lain sayang ga ada bonus TG sama case respon penjual baik utk segera kirim hanya pengiriman reguler yg gratis ongkir dptnya IdEx agk lama sempet khawatir blm smpe pdhal udh tinggl kirim ke rumah smpe kepending 1 hr secara umum cukup puas belanja dsini. Semoga awet berkah barokah utk semua. terimakasih ya penjual dan tokped idex 😃🙏🏻Tutup Ulasan',
 'barang masih segel, original, bagusss banget, sesuai request dpt yg kode PA/A, mimin nyaa fast respon bgt😍, pemakaian baru 2hari aman gaada troble dan kendala, semoga awettt🥰Tutup Ulasan',
 'Bagus bangettt. Walaupun ada beberapa kendala masalah pengiriman tapi bener bener bagus bangetttt. Dan pelayanannya sih yg top bangett. Selalu fast respon melayani customer bawel kaya gue hahaha. Sukses terus ismile \U0001faf0🏻Tutup Ulasan',
 'Top mantap. barang segel sangat rapihh. sinyal aman dan rapih pokonya top seller!',
 'barangnya original, dapat kode PA/A. dapat harga murah, cewek saya suka. dan penjual ramah',
 'barang masih segel ,,dapat kode PA/A nicee',
 'Barangnya sehari nyampe, ori, dan cs nya komunikatif. terima kasih',
 'Setelah kesana kesini nyari varian 256 yang sangat langka. Akhirnya dapet juga ditoko ini. Seller gercep. yang paling utama adalah IMEI Aman barang BNIB. Terima kasih 🙏.',
 'maaf baru sempet kasih ulasan. setelah sebulan pemakaian overall oke. wlpun masih harus banyak belajar ya wkwk  semoga awet di aku iPhonenya. ORI pasti. tapi aku beli dapet yang stok lama, bulan april. ku beli bulan agustus.   awalnya pilahpilih onlineshop mana yg trusted. setelah baca2 akhirnya pilih toko ini. disamping harga agak miring reviewnya bagus2 kok. Alhamdulillah masyaAllah Tabarakallah kebeli juga ini hp iPhone 🥲🥲  saran buat seller sih ya.. 🙏🏻 packingnya itu emang aman karna bubblenya yang tebel tapi kedepannya mungkin bisa ya dengan harga segitu dan asuransinya pengiriman yang terbilang lumayan kita bisa dapet packing kayu ya. atau nambah sedikit untuk dapat packing kayu. karna jujur sedikit takut ada tangan jahil gitu.  oh iya kemarin aku pakai ekspedisi SICEP*T yang next day. harapannya kan bisa dateng sehari setelahnya eeeeh ternyata sama aja dong. di hari setelahnya udah sampai di drop pointnya ngga buru2 dianter sama kurir, padahal paketnya pakai service next day kan. akhirnya karna takut was2 dll sore itu aku ambil langsung itu paket.   kecewa sih sama ekspedisinya. bayar ongkir mahal tp tetep aja sampainya 2 hari kalau aku ngga ambil sendiri langsung.   buat yang mau beli disini gak usah khawatir. bisa request apapun sama sellernya. pastikan pilih pengiriman yang cepat di kota kalian ya.   thankyou Ismile 🥰Tutup Ulasan',
 'mantap barang tersegel dan resmi indonesia',
 'Cs fast respon, barang sesuai, harga dibawah pasaran. Mantapp. Auto beli lagi pas iphone 20 rilis',
 'Barang sesuai pesanan dan sesuai request kode unit PA/A aman semua fungsi aman mantab pokoknya the best deh keren - Hitam 128 GB',
 'deg degan belinya via online.. biasanya on the spot\U0001fae3 tapi syukur barang sampai dengan aman sampai di tempat.. terima kasih iSmile👍🏻',
 'Recommended.. kiriman dg kurir gosend instant cepat.. walaupun sedikit butuh waktu untuk menanyakan jam dikirimkan.. chat dg admin sangat responsif.. boleh banget beli lagi di toko ini.. 😊👍🏻Tutup Ulasan',
 'gak pernah beli hp online harga 13 jutaan. karna murah, coba aja dulu semoga gak zonk. cpt banget. 3 hari udah nyampe. checkout langsung packing. setiap waktu mantengin ini tros udah dimana udah dimana. sampe kebawa mimpi sangking takutnya. alhamdulillah gak zonk. seneng banget. sesuai permintaan 0a/A (iBox). cuma kecewanya ini buatan China.Tutup Ulasan',
 '⚡️Proses cepat. 🚚 Pengiriman cepat. 📦 Packing baik. 👍 Kualitas OK.💲Harga Bagus. Terima kasih 🙏 Very Recommended!!!! Dapet di harga 13 jt, mantap!!!',
 'Alhamdulillah puas sekali belanja di sini, apalagi dapat harga 13,1jt masih dapat kembalian. Packing aman, pengiriman juga cepat sekali menggunakan paxel sehari sudah sampai Kediri. Pertama kali belanja online di atas 10jt no worry2 club.Tutup Ulasan',
 'bubble wrap tebell, pengiriman aman, semuanya ori. top bgttt!',
 'Product was delivered quickly and works perfectly',
 'barang okay.. fungsi aman sejauh ini.. baru sampai jd blm bnyk di cek.. smga aman dan awet',
 'Produk ini sangat berkualitas, awet, dan bermanfaat!',
 'hp asli dan resmi sdh dicek terdaftar.saran buat agan2 hati2 kalau beli online banyak no penipu mengatanamakan toko official store.saran kalau ada apa2 lsg japri saja toko via tokpedTutup Ulasan',
 'good seller, good shipment, overall good👍👍👍',
 'Alhamdulillah, nyampai dengan selamat, pengirimannya top deh, dari JKT ke SBY sehari sampai pakai jne next day. Packing tebel, admin cukup fast respon, thanks',
 'adminnya fast responn dan informatif, iphone ori garansi resmi, minusnya pengiriman cukup lama dan ga dapet bonus accessories',
 'Barang diterima dengan kondisi baik, tersegel, kondisi sesuai. Seller bantuin kirim walopun sedikit degdegan karena beli kesorean dan baru bisa dikirim besok pagi ke siang lumayan agak lama nunggu tapi amanTutup Ulasan',
 'Barang masih disegel dan ada garansi resminya, pengiriman tepat waktu, berfungsi dengan baik, pokokny mantap',
 'Diprosess dengan baik sesuai pesanan dan pengiriman cepat',
 'Iphone ORI dan garansi resmi Indo Seller fastrespon juga Namun pesan sameday lama sekali ketemu gojeknya, jadi ujung2nya pick up sendiri',
 'barang masih tersegel, packing tebel, pengiriman cepat, hp ori dan mulus, gas deh pokonya.',
 'barang masih disegel waktu sampai aman jg dr goncangan dan kejatuhan ada buble wrap, garansi on, imei aman, fitur premium, new in box, brg ori top, asli ibox, cmn minus nya di pengiriman,pesan dr tgl 11 malam, harus nya tgl 13 sampe, malah tgl 15 baru sampe, harus di komplain dulu baru gerak, dr pihak sellernya telat sehari utk proses hubungi kurir, ngendap sehari,kurirnya jg telat sehari utk jemput brg nya, pasti udh tau lah kurir mana yg sering bermasalh, slektif lg mikih kurirTutup Ulasan',
 'Produk ori, udah sebulan beli baru review. Minta garansi TAM diturutin. Pokoknya hanya bintang dan dokumentasi yg berbicara. Toko yg sangat recommended, bakal jadi langganan👍\U0001faf0Tutup Ulasan',
 'barang original & bagus, pelayanan oke, packing bubble wrap aman, pengiriman cepat. Dan beruntung banget dapet harga Promo. TOP BGT dah.',
 'barangnya masih di segel,produk berfungsi denganbaik,recomended seller👍👍👍',
 'Packagingnya tebel bgt bgt bgttt pokoknya puas makasiih',
 'barang ori & disegel rapi dengan keterangan nama barang dihilangkan utk menambah keamanan dari hal yg tidak diinginkan.',
 'toko elite pengiriman syulit parah beli instan dikirim 3 hari kemudian karena blmmrestok. TPI oke lah barangnya original cakep polll cakep cs nya kadang bener kadang gaje',
 'Barang masih segel, originil , semoga awet sayang ga ada bonusanya 🥲',
 'Modal nekat beli di toko yg gada offline storenya. tapi smua CS sangat membantu dan hpnya sampai dengan selamat. dri barang di pick up smpe diterima kerjaannya sejam mantengin live tracking eh ternyata drivernya cerita kalo beliau juga deg2an bawa hp ini haha Alhamdulillah smua aman, barang Ori garansi resmi Indo SA/A. Makasi ya untuk semua CS ismile sudah berhasil meyakini akkk kalo toko kalian sangat amanah🥰 sukses ya kalian!Tutup Ulasan',
 'pengiriman cepat, seller nya sangat komunikatif. walaupun gk dpt yg PA/A gpp ttp dpt garansi resmi terimakasih banyak admin 🙏🏼',
 'Barang ori, pelayanan memuaskan, sukaa',
 'Barang Mantap, Semoga Awet, Cuma Lama DiKurir Pick Up Saja. Thx',
 'barang bagus, asli, selamat sampi tujuan, resmi dan puas deh pokonya .. sampe order 2x .. thanks seller sukses terus',
 'barang mantap ori, lgs ada warantty nya dan dikasihnya yg ibox thankyou so much',
 'pake Jne Yes jakarta -makassar 1 hari benerN dong sampee, mimin fast respon, jawab sesuai yg ditanyain sat set lah pokoknya  dapat garansi TAM... terima kasih🙏🏻🙏🏻',
 'Alhamdulillah selamat, dikirim pake kurir toko, dipesen jam 12 jam 6an sudah sampai, kurir tokony cpt, barang saat sampe dalam kondisi baru dan lengkap. Rekomen kalo beli di toko ini. Deg2kan krn br pertama beli hape melalui online, tp ternyata good idea. Smg kedepannya semakin top markotopTutup Ulasan',
 'mantapp barngnya original..semoga awet.8',
 'bagus sih, cuma degdegan krn milih instant 3 jam hampir ga nyampe. wkwk tengkyu admin sudah diusahakan nyampe sebelum waktu caw',
 'pokoknya bintang 5 seperti review2 lainnya. top, recomended seller. terima kasih',
 'Resmiii,.mantappp  Akhirnya dapat yg pink',
 'Satu kata "GACOR" walaupun pengiriman agak lama ya tapi gapapa lah ya,dapet free TG sama Case',
 'terbaik dan cepat pengirimannya. recommended',
 'mantaap keren kak cuma lupa request kode sj mimin gercep  cuma lama di expedisi',
 'packing Mantap berlapis lapis bubblenya Warna sesuai pesanan dan Alhamdulillah dapat diskon 1jt',
 'Bintang 5 buat Toko nya..Barang nya Bintang 5 juga, Pengiriman Cepat..  Doain biar bisa beli lagi disini ya..  Makasih',
 'barang diterima dengan baik, original',
 'mantap, masih segel, ori',
 'Diterima dalam keadaan baik , garasi SA terima kasih',
 'barang masih segel dan packing lengkap banget seller fast respon dan sangat helpfull dan original resmi',
 'Barang masih disegel, garansi resmi, sesuai spesifikasi, sellernya ramah, fast respon, dan amanah.',
 'Barang masih disegel, garansi resmi, original. Seller ramah, proses cepat.',
 'Garansi resmi masih segel, seller fast respon dan jujur dalam menjelaskan pokoknya ga nyesel beli di toko ini',
 'Awalnya, saya mengalami masalah dengan HP yang tidak bisa mendapatkan sinyal seluler, meskipun sudah mencoba berbagai cara. Akhirnya, saya terpaksa melakukan reset pabrik. Namun, setelah reset, HP saya tidak dapat diaktivasi, sehingga tidak bisa digunakan sama sekali. Saya kemudian diarahkan ke bagian aftersales, dan petugasnya sangat ramah serta responsif. Tim aftersales menyarankan untuk melakukan retur secara manual karena status pemesanan di Tokopedia sudah selesai. Setelah melalui beberapa prosedur retur, HP saya diganti dengan unit yang baru. Dari segi pelayanan, saya sangat puas karena fast respond, dan tim aftersales memberikan layanan yang sangat baik dan ramah.Tutup Ulasan',
 'I love this store! Adminnya ramah, barang sesuai dengan yang tertera, original, pengirimannya juga tidak ngaret, dibantu juga jika ada problem teknis. Thank you ya!',
 'sesuai request dapet yang ID/A. super nice pengirimannya lama banget ampun ya Allah ya robi tapi overall semua aman barang tersegel garansi imei dll',
 'mantep si,  barang Ori, bisa self pickup (karena takut² klu pake jasa ekspedisi 😆) masih segel, sampe unboxing. cuma kelupaan kmarin harusnya skalian sama case nya haha. terima kasih ya, semoga awet di sayaTutup Ulasan',
 'asli barang ori gokill, mantap tokonya, sellernya juga membantu. rekomen pokoknya',
 'pelayanan sangat memuaskan, barang ori dan berfungsi normal',
 'IPhone 15 Harga Promo, semuanya resmi garansi Indonesia, harga disini yang terbaik.',
 'respon cepat, pengiriman barang cepat dan barang sesuai dengan deskripsi dan diterima dengan baik, kondisi 100 original',
 'Respon admin sangat cepat( tapi yg balas beda beda admin). Cuma disayangkan ga sesuai janji, bilang barang ready stock sisa 9, ternyata harus nunggu restock, janji akan dikirim dihari yg sama. Ternyata baru dikirim 2 hari kemudian. Ditambah sistem kurir rekomendasi dari Tokopedia ini yang paling menyebalkan bikin lama dan tidak update. Pengiriman dari ID express dioper ke JNE 5 hari baru sampai, bikin deg-degan. Karena yg dikirim hp yg ga murah. Takut hilang. Untuk Hp dapet kode PA/A sesuai request. Original bukan refurbish. Garansi langsung aktif. Tidak ada malfungsi. Untuk harga emang paling murah dari toko lain. Mantap. Packing aman pakai bubblewrap tebal.Tutup Ulasan',
 'garansi resmi, luar biasa.. admin responsif.. sukses selalu ya',
 'respon cepat proses juga cepat, barang mantap sesuai dengan pesanan. masi segel. ori ibox. Terima kasih seller rekomendasi.',
 'Okelah barang diterima lengkap, belum saya buka kardusnya, masih tersegel. Produk GDN resmi indonesia, dengan tambahan garansi 6 bulan dari keseluruhan kerusakan.. semoga awetTutup Ulasan',
 'Pengiriman tepat waktu, barang masih disegel dan berfungsi dengan baik. Ada kartu garansi nya juga',
 'Barangnya oke dan ori, kecepetan pengiriman juga mantep, adminnya responsif👍',
 'produk nya sesuai, pengirimannya aman banget! admin nya juga fast respon dan baik banget responnya padahal banyak nanya! pelayanannya juara bgt',
 'Pelayan seller terbaik dan ramah , barang original dan driver baik serta bertanggung jawab',
 'produk diterima dengan baik all fungsi oke yg paling penting garansi resmi',
 'Barang original, garansi resmi, masih segelan ...',
 'barang sesuai dengan pesanan, namun pengiriman agak lama memakai ID Express. mungkin bisa ditingkatkan kembali. but over all thank you🙏🏻',
 'Terima kasih iSmile pesanan sudah sampai. barang original. mulus kemasan bagus. cepat. seller recomend. pengiriman cepat',
 'Nice😍, Terimakasih brang sdh sampai sesuai pic dan deskripsi brnag original garansi resmi iBox, Brang dtg dgn aman packing sangat tebal brang sangat mulus, No cacat berdungsi dengan baik, Seller amanah, Fast respon terimakasih iSmile😊🙏Tutup Ulasan',
 'Iphone diterima dengan keadaan mulus tidak ada kekurangan. 100% recommended beli iphone paling murah di sini',
 'Seller nya sangat ramah, responsif, dan helpful. Pesen pakai instan dan dikasih beberapa mitigasi supaya pengirimannya aman. Packing nya juga super tebal jadi barang sampai tanpa lecet/rusak sedikitpun 👍🏻Tutup Ulasan',
 'Barangnya original, ada garansi resmi, barang baik sekali dan benar-benar dipacking dengan rapih dan tebal. Adminnya fast respon dan sangat informatif. Dapat tempered glass sama clear case juga dan bagus.. Worth it banget beli di sini, terima kasih ya kak iSmile dan kurir sehat selaluTutup Ulasan',
 'barang sesuai yang di pesan box tidak mulus ada yang penyok 2 sisi. padahal sudah di lapis bublewrap tebal. kemungkinan dari awal sudah cacat boxnya. mudahan hapenya aman.Tutup Ulasan',
 'alhamdulilah barang sesuai request, mulus gaada lecet sama sekali, cuman minus nya dipengiriman agak lama mungkin lagi delay overall bagus bgt',
 'paket tiba dengan selamat packing sangat rapi dan tebal, awal order sempat delay sehari pengiriman, tapi Alhamdulillah admin sangat fast respon  barang original resmi. semoga bisa bertahan lama. trmksh iSmileTutup Ulasan',
 'iPhone 15 adalah pilihan yang solid bagi pengguna yang menginginkan smartphone premium dengan performa tinggi, kualitas kamera yang luar biasa, dan desain yang elegan. Meskipun harganya lebih tinggi, fitur dan pengalaman pengguna yang ditawarkan membuatnya layak dipertimbangkan.Tutup Ulasan',
 'barang masi segel, ori n yang pasti Keren..Tengkyu seler',
 'Bagus sih, cakep banget unitnya. Pengiriman aman dan cepet, garansi juga jalan',
 'Barang original apple dan baru tersegel bukan inter atau bekas service, diterima dan dipakai tanpa kendala. Niat awal mau yg kode pa/a, di kirim yang kode sa/a tanpa request, lebih senang tentunya. Seri sa/a lebih bagus garansinya dan total tercover. Tinggal scan barcode garansi di dos iphonenya. Soal harga Ismile top banget. Thanks Ismile 👍👍👍Tutup Ulasan',
 'Barang ori, packing aman, pengiriman cepat. Very recommended',
 'Barang Asli Original, pengemasan baik, awalnya agak takut beli online, apalagi shiping jkt makassar 🥲 tapi alhamdulillah sampai tanpa ada kendala,',
 'oke banget, pelayanan cepat gak kayak toko sebelah',
 'Pengiriman cepat, packing tebal, masih segel',
 'Barang sudah pasti ori, garansi region Indonesia. Barang datang juga aman banget, bubble wrap nya tebel. Alasan bintang 4 karena konfirmasi warnanya yang dibeli ternyata kosong dan perlu konsumen yang aktif nanya dulu baru dikabarin 🙏🏻Tutup Ulasan',

## 1. TF-IDF Vectorization

In [7]:
vectorizer = TfidfVectorizer(max_features=100)
tfidf_matrix = vectorizer.fit_transform(ulasan)

# Konversi ke DataFrame
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())
tfidf_df.head()

,ada,admin,aja,alhamdulillah,aman,awet,bagus,baik,banget,barang,...,tidak,toko,top,tutup,udah,ulasan,waktu,ya,yang,yg
0,0.0,0.0,0.0,0.0,0.489805,0.0,0.000000,0.0,0.000000,0.164274,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0
1,0.0,0.0,0.0,0.0,0.176525,0.0,0.230316,0.0,0.000000,0.118408,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0
2,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.255768,0.126212,...,0.0,0.264047,0.0,0.0,0.0,0.000000,0.0,0.304518,0.0,0.0
3,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.009782,0.0,0.000000,0.0,0.0
4,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.153489,...,0.0,0.321115,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0

## 2. Word2Vec Embedding

In [8]:
# Tokenisasi sederhana
tokenized_ulasan = [ul.split() for ul in ulasan]

# Train model Word2Vec
w2v_model = Word2Vec(sentences=tokenized_ulasan, vector_size=100, window=5, min_count=1, workers=4)
w2v_vector = [sum([w2v_model.wv[word] for word in words if word in w2v_model.wv], 0) / len(words) for words in tokenized_ulasan]

# Konversi ke DataFrame
w2v_df = pd.DataFrame(w2v_vector)
w2v_df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.004824,0.013346,-0.001369,0.003328,0.000987,-0.018774,0.002371,0.027940,-0.009269,-0.007943,...,0.017211,0.010477,0.000552,-0.000279,0.022080,0.009444,0.006509,-0.012147,0.000417,0.000801
1,-0.003030,0.010919,-0.001142,0.000440,0.004345,-0.017424,0.003363,0.024642,-0.009213,-0.004367,...,0.018651,0.006089,0.001024,-0.000293,0.019835,0.008874,0.006635,-0.008788,-0.000504,0.001755
2,-0.000358,0.010699,0.002471,-0.000269,0.000868,-0.015437,0.001890,0.017736,-0.006075,-0.005015,...,0.013217,0.004001,-0.001653,0.000032,0.013580,0.005348,0.003955,-0.007419,-0.000844,-0.001547
3,0.008360,0.034106,0.007815,0.002189,0.005330,-0.026045,-0.009479,0.029024,-0.013380,0.003012,...,0.033686,-0.001537,-0.018127,-0.020814,0.005755,-0.009621,-0.001077,0.000230,-0.006468,-0.010823
4,-0.000207,0.004395,0.001011,-0.000163,0.001911,-0.007478,0.000575,0.011924,-0.003433,-0.003240,...,0.005970,0.002669,0.000712,0.000654,0.009671,0.000546,0.003228,-0.004793,0.000650,-0.000998

## 3. FastText Embedding

In [9]:
# Train model FastText
ft_model = FastText(sentences=tokenized_ulasan, vector_size=100, window=5, min_count=1, workers=4)
ft_vector = [sum([ft_model.wv[word] for word in words if word in ft_model.wv], 0) / len(words) for words in tokenized_ulasan]

# Konversi ke DataFrame
ft_df = pd.DataFrame(ft_vector)
ft_df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.242374,0.023350,0.121162,0.143110,0.229392,0.006956,0.184974,0.109566,0.011239,0.261271,...,-0.052418,-0.094409,-0.460073,-0.047112,-0.104253,0.447361,-0.183645,-0.352614,0.114001,0.252479
1,-0.235195,0.022649,0.118050,0.139308,0.223725,0.006837,0.180631,0.106781,0.011451,0.254100,...,-0.051036,-0.091949,-0.447552,-0.044782,-0.101040,0.434986,-0.178220,-0.342569,0.110567,0.245776
2,-0.230101,0.022146,0.114700,0.135438,0.218989,0.006852,0.175511,0.105559,0.011160,0.249088,...,-0.048713,-0.089718,-0.436545,-0.043957,-0.098332,0.424607,-0.174104,-0.334783,0.107652,0.239666
3,-0.208812,0.018405,0.097083,0.121433,0.193274,0.007999,0.150328,0.097083,0.011244,0.227462,...,-0.040966,-0.083517,-0.387551,-0.043091,-0.083375,0.375050,-0.151643,-0.299867,0.093569,0.208380
4,-0.136895,0.013181,0.068492,0.080779,0.129791,0.004082,0.104444,0.062127,0.006793,0.148162,...,-0.029221,-0.053682,-0.259719,-0.026232,-0.057959,0.251984,-0.103654,-0.198963,0.064450,0.141961